### ISSUE TITLE
Reminder: this module will crash for SDKv2 apps

### ISSUE THREAD

**Issue by RobinBol** [athombv/node-homey-log#2]
```
/Users/robinbolscher/Development/homey-client/opt/user/apps/81f4ebb3df0b48e5884efe7bb97b1a45/node_modules/homey-log/lib/Log.js:9
		if( typeof Homey.env.HOMEY_LOG_URL === 'string' ) {
		           ^


--- INFO: nl.eneco.toon has been killed ---
ReferenceError: Homey is not defined
    at new Log (/Users/robinbolscher/Development/homey-client/opt/user/apps/81f4ebb3df0b48e5884efe7bb97b1a45/node_modules/homey-log/lib/Log.js:9:14)
    at Object.<anonymous> (/Users/robinbolscher/Development/homey-client/opt/user/apps/81f4ebb3df0b48e5884efe7bb97b1a45/node_modules/homey-log/lib/Log.js:111:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.require (/Users/robinbolscher/Development/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:10:18)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/robinbolscher/Development/homey-client/opt/user/apps/81f4ebb3df0b48e5884efe7bb97b1a45/node_modules/homey-log/index.js:3:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.require (/Users/robinbolscher/Development/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:10:18)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/robinbolscher/Development/homey-client/opt/user/apps/81f4ebb3df0b48e5884efe7bb97b1a45/app.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.require (/Users/robinbolscher/Development/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:10:18)
    at require (internal/module.js:12:17)
    at /Users/robinbolscher/Development/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:226:23
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by WeeJeWel** [comment]
Fixed in https://github.com/athombv/node-homey-log/commit/3840b66b7abf28439add6da30deb8d3e9e6b3680
